### ISSUE TITLE
`@typescript-eslint/utils` is available and stable

### ISSUE THREAD

**Issue by yudai-nkt** [uhyo/eslint-plugin-tree-shakable#1]
I just had a small glance at the codebase, and wanted to let you know `@typescript-eslint/experimental-utils` isn't experimental anymore (just in case you didn't notice this). Excerpts from [the registry](https://www.npmjs.com/package/@typescript-eslint/experimental-utils):

> **This package is purely a re-export of `@typescript-eslint/utils`.** You should switch to importing from that non-experimental package instead.

**Comment by uhyo** [comment]
Wow thank you for information 🙂
I didn't notice that. 

I will soon switch to `@typescript-eslint/utils`.
